apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-09-06T16:54:06Z"
  labels:
    app: demo-nginx
  name: demo-nginx
  namespace: sre-demo
  resourceVersion: "139990"
  uid: 1f823d63-aeeb-412c-ba5d-e587f14cb7ff
spec:
  clusterIP: 10.96.52.252
  clusterIPs:
  - 10.96.52.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: demo-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
