apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana","namespace":"sre-demo"},"spec":{"ports":[{"port":3000,"targetPort":3000}],"selector":{"app":"grafana"}}}
  creationTimestamp: "2026-09-06T17:15:13Z"
  name: grafana
  namespace: sre-demo
  resourceVersion: "137009"
  uid: 264b8927-38c8-4f05-a96d-d7e6171003bf
spec:
  clusterIP: 10.96.139.63
  clusterIPs:
  - 10.96.139.63
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
