apiVersion: v1
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"apiVersion: 1\n\ndatasources:\n  - name: Prometheus\n    type: prometheus\n    access: proxy\n    url: http://prometheus:9090\n    isDefault: true\n    editable: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"grafana-datasource","namespace":"sre-demo"}}
  creationTimestamp: "2026-09-06T20:01:20Z"
  name: grafana-datasource
  namespace: sre-demo
  resourceVersion: "151935"
  uid: eec3f147-2baa-43a8-859d-763c7955000e
