apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-09-06T16:54:05Z"
  labels:
    kubernetes.io/metadata.name: sre-demo
  name: sre-demo
  resourceVersion: "134876"
  uid: f450ccbc-b9db-470f-a909-e3a9da72eca7
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
